- hosts: localhost
  connection: local
  tasks:
    - name: 'update sshd_config'
      lineinfile:
        dest: /etc/ssh/sshd_config
        state: present
        backrefs: yes
        regexp: '{{ item.regexp }}'
        line: '{{ item.line }}'
      with_items:
        - regexp: '^#?Protocol\s'
          line: 'Protocol 2'
        - regexp: '^#?PermitRootLogin\s'
          line: 'PermitRootLogin no'
        - regexp: '^#?PasswordAuthentication\s'
          line: 'PasswordAuthentication no'
        - regexp: '^#?PermitEmptyPasswords\s'
          line: 'PermitEmptyPasswords no'
    - name: 'restart sshd'
      systemd:
        name: sshd.service
        state: restarted
        daemon_reload: yes
