# https://docs.docker.com/engine/installation/linux/docker-ce/centos/
- hosts: localhost
  connection: local
  tasks:
    - name: 'install required packages'
      yum:
        name: '{{ item }}'
        state: latest
      with_items:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
    - name: add docker repo
      shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
      args:
        chdir: "/etc/yum.repos.d"
        creates: docker-ce.repo
    - name: 'install docker-ce'
      yum:
        name: docker-ce
        state: latest
    - name: 'start docker'
      systemd:
        name: docker.service
        state: restarted
        daemon_reload: yes
        enabled: yes
